development:
  adapter: postgresql
  database: buzzbands_development
  username: evan
  password: password
  host: localhost
test:
  adapter: postgresql
  database: buzzbands_test
  username: evan
  password: password
  host: localhost
production:
  adapter: postgresql
  database: buzzbands_production
  username: evan
  password: password
  host: localhost
